encoding: utf-8
#url: 'https://pages.github.coecis.cornell.edu/cs5450/website'
url: 'https://cs5450.github.io'
#url: 'http://localhost:4000'
timezone: America/New_York
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: none
paginate_path: 'page:num'
exclude: ['.gitignore', 'README.md', 'LICENSE.md', 'Gemfile']
