encoding: utf-8
 url: 'https://pages.github.coecis.cornell.edu/cs5450/website/'
#url: 'http://localhost:4000'
timezone: America/New_York
markdown: kramdown
redcarpet:
  extensions: ['no_intra_emphasis', 'fenced_code_blocks', 'autolink', 'tables', 'with_toc_data']
highlighter: rouge
permalink: none
paginate_path: 'page:num'
exclude: ['.gitignore', 'README.md', 'LICENSE.md']
