encoding: utf-8
url: 'https://cs5435.github.io'
timezone: America/New_York
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: none
paginate_path: 'page:num'
exclude: ['.gitignore', 'README.md', 'LICENSE.md', 'Gemfile']

theme: jekyll-theme-cayman
