encoding: utf-8
url: 'https://pages.github.coecis.cornell.edu/cs5450/website/'
timezone: America/Los_Angeles
redcarpet:
  extensions: ['no_intra_emphasis', 'fenced_code_blocks', 'autolink', 'tables', 'with_toc_data']
highlighter: rogue
permalink: none
paginate_path: 'page:num'
exclude: ['.gitignore', 'README.md', 'LICENSE.md']
